spring:
  datasource:
    url: jdbc:mysql://192.168.2.14:3306/vcsaas_learn?characterEncoding=UTF-8
    username: db-test
    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
    dbcp2:
      validation-query: select 1
    jndi-name: jdbc/MySQL
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database: default
server:
  port: 9522
spring:
  thymeleaf:
    cache: false
app:
  datasource:
    jdbc-url: jdbc:mysql://192.168.2.14:3306/vcsaas_learn?characterEncoding=UTF-8
    username: db-test
    password: 123456
    maximum-pool-size: 30
jpa:
  show-sql: true
